/* MPBP440 V6.3 — Injection refonte ergonomique */
(function(){
function createV63Home(){
 if(document.querySelector(".mpbp-v63-hero"))return;
 const target=document.querySelector("main")||document.body;
 const hero=document.createElement("section");hero.className="mpbp-v63-hero";hero.innerHTML=`<div class="mpbp-v63-top"><div class="mpbp-v63-logo-card"><img src="/assets/brand/mpbp440-official-logo.webp" alt="Logo officiel MPBP440"></div><div class="mpbp-v63-title"><p>Portail musical officiel</p><h1>MPBP 440 Corp.</h1><strong>Label indépendant — Sparetdee Simon • Juste Une Plume</strong><div class="mpbp-v63-artists"><a class="mpbp-v63-artist-card" href="/artistes/sparetdee-simon.html"><img src="/assets/brand/mpbp440-official-logo.webp" alt="Sparetdee Simon"><div><h3>Sparetdee Simon</h3><p>Rap conscient • Roots • Vibration</p></div></a><a class="mpbp-v63-artist-card" href="/artistes/juste-une-plume.html"><img src="/assets/icons/mpbp440-app-icon.webp" alt="Juste Une Plume"><div><h3>Juste Une Plume</h3><p>Écriture • émotion • plume symbolique</p></div></a></div></div></div>`;
 const releases=document.createElement("section");releases.className="mpbp-v63-section";releases.innerHTML=`<p>Comptes à rebours officiels</p><h2>Prochaines sorties</h2><div class="mpbp-v63-release-grid"><article class="mpbp-v63-release"><img src="/assets/covers/reves-et-cauchemards.webp" alt="Rêves et Cauchemards"><div class="mpbp-v63-content"><h3>Rêves et Cauchemards</h3><p>Sparetdee Simon — sortie officielle prévue le <strong>24/06/2026</strong>.</p><a class="mpbp-v63-btn" href="/music/index.html">Voir dans Music Hub</a></div></article><article class="mpbp-v63-release"><div class="mpbp-v63-content"><h3>Le Système</h3><p>Sparetdee Simon — sortie officielle prévue le <strong>27/06/2026</strong>.</p><a class="mpbp-v63-btn ghost" href="/music/index.html">Voir la sortie</a></div></article></div>`;
 const music=document.createElement("section");music.className="mpbp-v63-section";music.innerHTML=`<p>Bibliothèque officielle</p><h2>Titres disponibles</h2><div class="mpbp-v63-music-grid"><article class="mpbp-v63-track"><img src="/assets/covers/je-vous-pousse-tous.webp" alt="Je Vous Pousse Tous"><div class="mpbp-v63-content"><h3>Je Vous Pousse Tous</h3><p>Disponible sur toutes les plateformes.</p><a class="mpbp-v63-btn" href="/artistes/sparetdee-simon.html">Page artiste</a></div></article><article class="mpbp-v63-track"><img src="/assets/covers/l-argent.webp" alt="L'Argent"><div class="mpbp-v63-content"><h3>L’Argent</h3><p>Disponible sur toutes les plateformes.</p><a class="mpbp-v63-btn" href="/artistes/sparetdee-simon.html">Page artiste</a></div></article></div>`;
 const tv=document.createElement("section");tv.className="mpbp-v63-section";tv.innerHTML=`<p>MPBP TV</p><h2>Exclusivités du site</h2><article class="mpbp-v63-tv-card"><h3>Clips exclusifs bientôt disponibles</h3><p>Les clips MP4 locaux pourront être ajoutés plus tard dans <code>assets/videos/</code> et affichés directement dans MPBP TV.</p><a class="mpbp-v63-btn ghost" href="/mpbp-tv/index.html">Ouvrir MPBP TV</a></article>`;
 target.prepend(tv);target.prepend(music);target.prepend(releases);target.prepend(hero);
}
document.addEventListener("DOMContentLoaded",createV63Home);
})();
